name: Selenium Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"  # Run at 12 PM UTC every day

jobs: 
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install selenium==4.29.0 pandas==2.2.3 openpyxl==3.1.5 filelock==3.18.0
          wget -q https://chromedriver.storage.googleapis.com/115.0.5790.170/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          echo "Dependencies installed."

      - name: Set Up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "Chrome installed."

      - name: Run Automation Script
        run: |
          python fundingpips_automation.py
          echo "Automation script executed."
